Repository geekymeeky/chitchat, pull requests merged in 2021-07, with the labels that each got.

#14 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: DCP 2021

#12 Update README.md
  README.md
Labels: DCP 2021, documentation, needs-more-info

#24 Added README file
  README.md
Labels: DCP 2021, Level1

#30 Login Page fixed
  lib/screens/login_screen.dart
Labels: DCP 2021, Level0

#31 Added Chat Screen
  lib/screens/chat_screen.dart
  lib/utils/constants.dart
Labels: Level2
